### ISSUE TITLE
Python 3.7 install fails due to Cython-generated cpp file in sdist

### ISSUE THREAD

**Issue by skogler** [HearthSim/decrunch#10]
Unfortunately, the PyPi package contains a file named `decrunch.cpp`. 
he problem is that this file was generated with an old version of Cython which generates code incompatible with Python 3.7.

If I remove `decrunch.cpp`, I can install the package as usual.

Maybe the solution is to just regenerate the file with a new Cython version.

To be precise, the error when installing is the following:

```
decrunch.cpp:3561:69: error: too many arguments to function
       return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                                                                       ^
  error: command 'gcc' failed with exit status 1
```

**Comment by jleclanche** [comment]
Fixed in 0.3.1
