### ISSUE TITLE
ETC2 crunched support

### ISSUE THREAD

**Issue by K0lb3** [HearthSim/decrunch#11]
Atm decrunch doesn't support crunched versions of ETC2.

Addition to decrunch.pyx Format:
	ETC1 = 10
	ETC2 = 11
	ETC2A = 12
  	ETC1S = 13
  	ETC2AS = 14

The /crunch code from [Unity-Technologies/crunch](https://github.com/Unity-Technologies/crunch/tree/unity) results in a build error.

**Comment by K0lb3** [comment]
I replaced some parts of the old crn_decomp.h with parts of the new one from Unity-Technology and also replaced the other 2 files with those from Unity-Tech.

The result looks fine,
it can decode crunched ETC2 now.

[crunch.zip](https://github.com/HearthSim/decrunch/files/3007135/crunch.zip)

It also works in concert with [Unitypack/Adds ability to decompress ETC and ETC2 images](https://github.com/HearthSim/UnityPack/pull/52) pull request.

**Comment by jleclanche** [comment]
Implemented in 6a21030f86fda86dd7c8bf51cfbab49a23487973
