### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by ghost** [HearthSim/decrunch#3]
`pip install decrunch`
gives the following output (on Windows 10 1607 & Python 3.6.1):
`Running setup.py (path:%USERPROFILE%\AppData\Local\Temp\pip-build-wxg4s8ak\decrunch\setup.py) egg_info for package decrunch produced metadata for project name unknown. Fix your #egg=decrunch fragments.
  Requirement already satisfied (use --upgrade to upgrade): unknown from https://pypi.python.org/packages/7b/0f/ea88026a5e2340eb45df1289e67c925e551158244728abdb7107d946f294/decrunch-0.2.1.tar.gz#md5=1e189a72d122fafc1717e6781c1567e2 in %USERPROFILE%\appdata\local\programs\python\python36-32\lib\site-packages`

**Comment by jleclanche** [comment]
Run `pip install --upgrade pip setuptools wheel` before installing decrunch.
