### ISSUE TITLE
Malloc.h replaced by stdlib.h while installing

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/decrunch#9]
@danielfrausto commented on [Fri Feb 02 2018](https://github.com/HearthSim/UnityPack/issues/69)

Hi , while trying to install scrunch, I get the error "malloc.h replaced by stdlib.h" while installing. Using freebsd 11.1 and python3.

**Comment by jleclanche** [comment]
@danielfrausto Can you PR an ifdef for freebsd? It should be straightforward but I have no way to test it myself here.

**Comment by danielfrausto** [comment]
@jleclanche I have modified crn_decomp.cpp to this...

```c
#define _CRT_SECURE_NO_WARNINGS
#include <string.h>
#if !defined(__APPLE__)
#if defined(__FreeBSD__)
#include <stdlib.h>
#else
#include <malloc.h>
#endif
#ifdef _WIN32
#define malloc_usable_size _msize
#endif
#endif

#include "crn_decomp.h"
```

and in crunch/crn_decomp.h include <stdlib.h> is already set.

Sorry , I am new to python.
